BEGIN TRANSACTION;


-- Adds all regions.
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Afghanistan','AF');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Aland Islands','AX');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Albania','AL');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Algeria','DZ');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('American Samoa','AS');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Andorra','AD');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Angola','AO');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Anguilla','AI');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Antarctica','AQ');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Antigua And Barbuda','AG');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Argentina','AR');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Armenia','AM');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Aruba','AW');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Australia','AU');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Austria','AT');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Azerbaijan','AZ');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Bahamas','BS');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Bahrain','BH');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Bangladesh','BD');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Barbados','BB');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Belarus','BY');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Belgium','BE');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Belize','BZ');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Benin','BJ');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Bermuda','BM');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Bhutan','BT');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Bolivia','BO');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Bosnia And Herzegovina','BA');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Botswana','BW');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Bouvet Island','BV');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Brazil','BR');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('British Indian Ocean Territory','IO');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Brunei Darussalam','BN');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Bulgaria','BG');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Burkina Faso','BF');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Burundi','BI');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Cambodia','KH');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Cameroon','CM');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Canada','CA');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Cape Verde','CV');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Cayman Islands','KY');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Central African Republic','CF');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Chad','TD');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Chile','CL');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('China','CN');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Christmas Island','CX');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Cocos (Keeling) Islands','CC');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Colombia','CO');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Comoros','KM');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Congo','CG');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Congo, The Democratic Republic Of The','CD');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Cook Islands','CK');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Costa Rica','CR');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Cote D''Ivoire','CI');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Croatia','HR');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Cuba','CU');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Cyprus','CY');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Czech Republic','CZ');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Denmark','DK');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Djibouti','DJ');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Dominica','DM');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Dominican Republic','DO');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Ecuador','EC');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Egypt','EG');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('El Salvador','SV');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Equatorial Guinea','GQ');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Eritrea','ER');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Estonia','EE');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Ethiopia','ET');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Falkland Islands (Malvinas)','FK');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Faroe Islands','FO');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Fiji','FJ');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Finland','FI');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('France','FR');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('French Guiana','GF');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('French Polynesia','PF');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('French Southern Territories','TF');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Gabon','GA');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Gambia','GM');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Georgia','GE');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Germany','DE');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Ghana','GH');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Gibraltar','GI');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Greece','GR');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Greenland','GL');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Grenada','GD');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Guadeloupe','GP');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Guam','GU');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Guatemala','GT');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Guernsey','GG');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Guinea','GN');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Guinea-Bissau','GW');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Guyana','GY');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Haiti','HT');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Heard Island And Mcdonald Islands','HM');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Holy See (Vatican City State)','VA');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Honduras','HN');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Hong Kong','HK');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Hungary','HU');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Iceland','IS');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('India','IN');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Indonesia','ID');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Iran, Islamic Republic Of','IR');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Iraq','IQ');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Ireland','IE');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Isle Of Man','IM');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Israel','IL');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Italy','IT');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Jamaica','JM');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Japan','JP');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Jersey','JE');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Jordan','JO');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Kazakhstan','KZ');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Kenya','KE');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Kiribati','KI');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Korea, Democratic People''s Republic Of','KP');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Korea, Republic Of','KR');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Kuwait','KW');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Kyrgyzstan','KG');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Lao People''s Democratic Republic','LA');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Latvia','LV');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Lebanon','LB');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Lesotho','LS');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Liberia','LR');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Libyan Arab Jamahiriya','LY');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Liechtenstein','LI');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Lithuania','LT');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Luxembourg','LU');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Macao','MO');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Macedonia, The Former Yugoslav Republic Of','MK');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Madagascar','MG');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Malawi','MW');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Malaysia','MY');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Maldives','MV');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Mali','ML');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Malta','MT');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Marshall Islands','MH');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Martinique','MQ');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Mauritania','MR');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Mauritius','MU');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Mayotte','YT');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Mexico','MX');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Micronesia, Federated States Of','FM');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Moldova, Republic Of','MD');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Monaco','MC');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Mongolia','MN');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Montserrat','MS');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Morocco','MA');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Mozambique','MZ');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Myanmar','MM');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Namibia','NA');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Nauru','NR');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Nepal','NP');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Netherlands','NL');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Netherlands Antilles','AN');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('New Caledonia','NC');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('New Zealand','NZ');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Nicaragua','NI');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Niger','NE');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Nigeria','NG');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Niue','NU');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Norfolk Island','NF');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Northern Mariana Islands','MP');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Norway','NO');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Oman','OM');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Pakistan','PK');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Palau','PW');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Palestinian Territory, Occupied','PS');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Panama','PA');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Papua New Guinea','PG');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Paraguay','PY');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Peru','PE');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Philippines','PH');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Pitcairn','PN');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Poland','PL');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Portugal','PT');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Puerto Rico','PR');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Qatar','QA');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Reunion','RE');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Romania','RO');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Russian Federation','RU');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Rwanda','RW');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Saint Helena','SH');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Saint Kitts And Nevis','KN');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Saint Lucia','LC');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Saint Pierre And Miquelon','PM');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Saint Vincent And The Grenadines','VC');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Samoa','WS');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('San Marino','SM');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Sao Tome And Principe','ST');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Saudi Arabia','SA');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Senegal','SN');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Serbia And Montenegro','CS');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Seychelles','SC');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Sierra Leone','SL');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Singapore','SG');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Slovakia','SK');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Slovenia','SI');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Solomon Islands','SB');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Somalia','SO');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('South Africa','ZA');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('South Georgia And The South Sandwich Islands','GS');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Spain','ES');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Sri Lanka','LK');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Sudan','SD');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Suriname','SR');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Svalbard And Jan Mayen','SJ');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Swaziland','SZ');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Sweden','SE');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Switzerland','CH');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Syrian Arab Republic','SY');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Taiwan, Province Of China','TW');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Tajikistan','TJ');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Tanzania, United Republic Of','TZ');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Thailand','TH');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Timor-Leste','TL');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Togo','TG');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Tokelau','TK');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Tonga','TO');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Trinidad And Tobago','TT');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Tunisia','TN');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Turkey','TR');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Turkmenistan','TM');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Turks And Caicos Islands','TC');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Tuvalu','TV');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Uganda','UG');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Ukraine','UA');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('United Arab Emirates','AE');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('United Kingdom','GB');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('United States','US');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('United States Minor Outlying Islands','UM');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Uruguay','UY');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Uzbekistan','UZ');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Vanuatu','VU');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Venezuela','VE');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Viet Nam','VN');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Virgin Islands, British','VG');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Virgin Islands, U.S.','VI');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Wallis And Futuna','WF');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Western Sahara','EH');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Yemen','YE');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Zambia','ZM');
INSERT INTO "Regions" ("regionName","regionCode") VALUES ('Zimbabwe','ZW');


COMMIT;