BEGIN TRANSACTION;


-- Adds Locations
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Afghanistan','AF','Afghanistan','AF');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Aland Islands','AX','Aland Islands','AX');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Albania','AL','Albania','AL');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Algeria','DZ','Algeria','DZ');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('American Samoa','AS','American Samoa','AS');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Andorra','AD','Andorra','AD');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Angola','AO','Angola','AO');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Anguilla','AI','Anguilla','AI');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Antarctica','AQ','Antarctica','AQ');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Antigua And Barbuda','AG','Antigua And Barbuda','AG');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Argentina','AR','Argentina','AR');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Armenia','AM','Armenia','AM');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Aruba','AW','Aruba','AW');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Australia','AU','Australia','AU');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Austria','AT','Austria','AT');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Azerbaijan','AZ','Azerbaijan','AZ');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Bahamas','BS','Bahamas','BS');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Bahrain','BH','Bahrain','BH');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Bangladesh','BD','Bangladesh','BD');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Barbados','BB','Barbados','BB');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Belarus','BY','Belarus','BY');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Belgium','BE','Belgium','BE');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Belize','BZ','Belize','BZ');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Benin','BJ','Benin','BJ');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Bermuda','BM','Bermuda','BM');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Bhutan','BT','Bhutan','BT');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Bolivia','BO','Bolivia','BO');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Bosnia And Herzegovina','BA','Bosnia And Herzegovina','BA');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Botswana','BW','Botswana','BW');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Bouvet Island','BV','Bouvet Island','BV');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Brazil','BR','Brazil','BR');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('British Indian Ocean Territory','IO','British Indian Ocean Territory','IO');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Brunei Darussalam','BN','Brunei Darussalam','BN');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Bulgaria','BG','Bulgaria','BG');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Burkina Faso','BF','Burkina Faso','BF');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Burundi','BI','Burundi','BI');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Cambodia','KH','Cambodia','KH');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Cameroon','CM','Cameroon','CM');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Canada','CA','Canada','CA');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Cape Verde','CV','Cape Verde','CV');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Cayman Islands','KY','Cayman Islands','KY');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Central African Republic','CF','Central African Republic','CF');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Chad','TD','Chad','TD');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Chile','CL','Chile','CL');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('China','CN','China','CN');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Christmas Island','CX','Christmas Island','CX');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Cocos (Keeling) Islands','CC','Cocos (Keeling) Islands','CC');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Colombia','CO','Colombia','CO');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Comoros','KM','Comoros','KM');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Congo','CG','Congo','CG');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Congo, The Democratic Republic Of The','CD','Congo, The Democratic Republic Of The','CD');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Cook Islands','CK','Cook Islands','CK');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Costa Rica','CR','Costa Rica','CR');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Cote D''Ivoire','CI','Cote D''Ivoire','CI');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Croatia','HR','Croatia','HR');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Cuba','CU','Cuba','CU');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Cyprus','CY','Cyprus','CY');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Czech Republic','CZ','Czech Republic','CZ');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Denmark','DK','Denmark','DK');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Djibouti','DJ','Djibouti','DJ');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Dominica','DM','Dominica','DM');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Dominican Republic','DO','Dominican Republic','DO');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Ecuador','EC','Ecuador','EC');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Egypt','EG','Egypt','EG');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('El Salvador','SV','El Salvador','SV');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Equatorial Guinea','GQ','Equatorial Guinea','GQ');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Eritrea','ER','Eritrea','ER');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Estonia','EE','Estonia','EE');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Ethiopia','ET','Ethiopia','ET');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Falkland Islands (Malvinas)','FK','Falkland Islands (Malvinas)','FK');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Faroe Islands','FO','Faroe Islands','FO');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Fiji','FJ','Fiji','FJ');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Finland','FI','Finland','FI');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('France','FR','France','FR');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('French Guiana','GF','French Guiana','GF');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('French Polynesia','PF','French Polynesia','PF');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('French Southern Territories','TF','French Southern Territories','TF');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Gabon','GA','Gabon','GA');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Gambia','GM','Gambia','GM');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Georgia','GE','Georgia','GE');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Germany','DE','Germany','DE');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Ghana','GH','Ghana','GH');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Gibraltar','GI','Gibraltar','GI');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Greece','GR','Greece','GR');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Greenland','GL','Greenland','GL');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Grenada','GD','Grenada','GD');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Guadeloupe','GP','Guadeloupe','GP');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Guam','GU','Guam','GU');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Guatemala','GT','Guatemala','GT');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Guernsey','GG','Guernsey','GG');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Guinea','GN','Guinea','GN');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Guinea-Bissau','GW','Guinea-Bissau','GW');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Guyana','GY','Guyana','GY');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Haiti','HT','Haiti','HT');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Heard Island And Mcdonald Islands','HM','Heard Island And Mcdonald Islands','HM');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Holy See (Vatican City State)','VA','Holy See (Vatican City State)','VA');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Honduras','HN','Honduras','HN');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Hong Kong','HK','Hong Kong','HK');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Hungary','HU','Hungary','HU');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Iceland','IS','Iceland','IS');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('India','IN','India','IN');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Indonesia','ID','Indonesia','ID');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Iran, Islamic Republic Of','IR','Iran, Islamic Republic Of','IR');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Iraq','IQ','Iraq','IQ');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Ireland','IE','Ireland','IE');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Isle Of Man','IM','Isle Of Man','IM');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Israel','IL','Israel','IL');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Italy','IT','Italy','IT');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Jamaica','JM','Jamaica','JM');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Japan','JP','Japan','JP');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Jersey','JE','Jersey','JE');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Jordan','JO','Jordan','JO');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Kazakhstan','KZ','Kazakhstan','KZ');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Kenya','KE','Kenya','KE');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Kiribati','KI','Kiribati','KI');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Korea, Democratic People''s Republic Of','KP','Korea, Democratic People''s Republic Of','KP');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Korea, Republic Of','KR','Korea, Republic Of','KR');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Kuwait','KW','Kuwait','KW');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Kyrgyzstan','KG','Kyrgyzstan','KG');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Lao People''s Democratic Republic','LA','Lao People''s Democratic Republic','LA');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Latvia','LV','Latvia','LV');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Lebanon','LB','Lebanon','LB');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Lesotho','LS','Lesotho','LS');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Liberia','LR','Liberia','LR');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Libyan Arab Jamahiriya','LY','Libyan Arab Jamahiriya','LY');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Liechtenstein','LI','Liechtenstein','LI');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Lithuania','LT','Lithuania','LT');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Luxembourg','LU','Luxembourg','LU');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Macao','MO','Macao','MO');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Macedonia, The Former Yugoslav Republic Of','MK','Macedonia, The Former Yugoslav Republic Of','MK');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Madagascar','MG','Madagascar','MG');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Malawi','MW','Malawi','MW');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Malaysia','MY','Malaysia','MY');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Maldives','MV','Maldives','MV');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Mali','ML','Mali','ML');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Malta','MT','Malta','MT');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Marshall Islands','MH','Marshall Islands','MH');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Martinique','MQ','Martinique','MQ');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Mauritania','MR','Mauritania','MR');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Mauritius','MU','Mauritius','MU');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Mayotte','YT','Mayotte','YT');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Mexico','MX','Mexico','MX');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Micronesia, Federated States Of','FM','Micronesia, Federated States Of','FM');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Moldova, Republic Of','MD','Moldova, Republic Of','MD');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Monaco','MC','Monaco','MC');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Mongolia','MN','Mongolia','MN');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Montserrat','MS','Montserrat','MS');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Morocco','MA','Morocco','MA');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Mozambique','MZ','Mozambique','MZ');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Myanmar','MM','Myanmar','MM');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Namibia','NA','Namibia','NA');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Nauru','NR','Nauru','NR');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Nepal','NP','Nepal','NP');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Netherlands','NL','Netherlands','NL');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Netherlands Antilles','AN','Netherlands Antilles','AN');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('New Caledonia','NC','New Caledonia','NC');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('New Zealand','NZ','New Zealand','NZ');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Nicaragua','NI','Nicaragua','NI');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Niger','NE','Niger','NE');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Nigeria','NG','Nigeria','NG');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Niue','NU','Niue','NU');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Norfolk Island','NF','Norfolk Island','NF');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Northern Mariana Islands','MP','Northern Mariana Islands','MP');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Norway','NO','Norway','NO');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Oman','OM','Oman','OM');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Pakistan','PK','Pakistan','PK');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Palau','PW','Palau','PW');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Palestinian Territory, Occupied','PS','Palestinian Territory, Occupied','PS');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Panama','PA','Panama','PA');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Papua New Guinea','PG','Papua New Guinea','PG');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Paraguay','PY','Paraguay','PY');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Peru','PE','Peru','PE');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Philippines','PH','Philippines','PH');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Pitcairn','PN','Pitcairn','PN');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Poland','PL','Poland','PL');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Portugal','PT','Portugal','PT');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Puerto Rico','PR','Puerto Rico','PR');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Qatar','QA','Qatar','QA');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Reunion','RE','Reunion','RE');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Romania','RO','Romania','RO');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Russian Federation','RU','Russian Federation','RU');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Rwanda','RW','Rwanda','RW');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Saint Helena','SH','Saint Helena','SH');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Saint Kitts And Nevis','KN','Saint Kitts And Nevis','KN');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Saint Lucia','LC','Saint Lucia','LC');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Saint Pierre And Miquelon','PM','Saint Pierre And Miquelon','PM');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Saint Vincent And The Grenadines','VC','Saint Vincent And The Grenadines','VC');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Samoa','WS','Samoa','WS');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('San Marino','SM','San Marino','SM');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Sao Tome And Principe','ST','Sao Tome And Principe','ST');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Saudi Arabia','SA','Saudi Arabia','SA');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Senegal','SN','Senegal','SN');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Serbia And Montenegro','CS','Serbia And Montenegro','CS');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Seychelles','SC','Seychelles','SC');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Sierra Leone','SL','Sierra Leone','SL');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Singapore','SG','Singapore','SG');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Slovakia','SK','Slovakia','SK');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Slovenia','SI','Slovenia','SI');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Solomon Islands','SB','Solomon Islands','SB');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Somalia','SO','Somalia','SO');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('South Africa','ZA','South Africa','ZA');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('South Georgia And The South Sandwich Islands','GS','South Georgia And The South Sandwich Islands','GS');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Spain','ES','Spain','ES');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Sri Lanka','LK','Sri Lanka','LK');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Sudan','SD','Sudan','SD');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Suriname','SR','Suriname','SR');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Svalbard And Jan Mayen','SJ','Svalbard And Jan Mayen','SJ');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Swaziland','SZ','Swaziland','SZ');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Sweden','SE','Sweden','SE');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Switzerland','CH','Switzerland','CH');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Syrian Arab Republic','SY','Syrian Arab Republic','SY');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Taiwan, Province Of China','TW','Taiwan, Province Of China','TW');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Tajikistan','TJ','Tajikistan','TJ');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Tanzania, United Republic Of','TZ','Tanzania, United Republic Of','TZ');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Thailand','TH','Thailand','TH');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Timor-Leste','TL','Timor-Leste','TL');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Togo','TG','Togo','TG');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Tokelau','TK','Tokelau','TK');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Tonga','TO','Tonga','TO');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Trinidad And Tobago','TT','Trinidad And Tobago','TT');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Tunisia','TN','Tunisia','TN');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Turkey','TR','Turkey','TR');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Turkmenistan','TM','Turkmenistan','TM');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Turks And Caicos Islands','TC','Turks And Caicos Islands','TC');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Tuvalu','TV','Tuvalu','TV');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Uganda','UG','Uganda','UG');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Ukraine','UA','Ukraine','UA');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('United Arab Emirates','AE','United Arab Emirates','AE');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('United Kingdom','GB','United Kingdom','GB');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('United States','US','United States','US');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('United States Minor Outlying Islands','UM','United States Minor Outlying Islands','UM');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Uruguay','UY','Uruguay','UY');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Uzbekistan','UZ','Uzbekistan','UZ');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Vanuatu','VU','Vanuatu','VU');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Venezuela','VE','Venezuela','VE');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Viet Nam','VN','Viet Nam','VN');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Virgin Islands, British','VG','Virgin Islands, British','VG');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Virgin Islands, U.S.','VI','Virgin Islands, U.S.','VI');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Wallis And Futuna','WF','Wallis And Futuna','WF');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Western Sahara','EH','Western Sahara','EH');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Yemen','YE','Yemen','YE');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Zambia','ZM','Zambia','ZM');
INSERT INTO "Location" ("locationName","locationCode","regionName","regionCode") VALUES ('Zimbabwe','ZW','Zimbabwe','ZW');

COMMIT TRANSACTION;
